name: Deploy React + Vite to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger workflow on push to the master branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Используйте v3 или более позднюю

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Используйте v3 или более позднюю
        with:
          node-version: '18' # Рекомендуется использовать LTS версию Node.js (например, 18)

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # Выполняем команду сборки, указанную в package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Папка, в которой находится собранный Vite проект (обычно 'dist')
          force_orphan: true # Это ОЧЕНЬ ВАЖНО для правильной работы
          publish_branch: gh-pages # Указываем ветку, в которую будет развернут сайт